[build]
  command = "pip install -r requirements.txt && pelican content -o output -s pelicanconf.py && cp -r content/admin output/"
  publish = "output"

[build.environment]
  PYTHON_VERSION = "3.11"

# Local redirects for admin functionality
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Block indexing with robots.txt
[[redirects]]
  from = "/robots.txt"
  to = "/netlify-robots.txt"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # SEO blocking headers - prevent indexing
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet, noimageindex"

# Admin page headers for CMS
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
