[build]
  command = "pip install -r requirements.txt && pelican content -o output -s pelicanconf.py"
  publish = "output"

[build.environment]
  PYTHON_VERSION = "3.11"

# Redirects for better URL handling
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Admin page headers for CMS
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
