backend:
  name: git-gateway
  branch: main

media_folder: "content/images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary_fields: ["title", "date", "category", "summary"]
    sortable_fields: ["date", "title", "category", "author"]
    view_filters:
      - label: "All Articles"
        field: title
        pattern: ".*"
      - label: "Published This Year"
        field: date
        pattern: "2025"
      - label: "Published Last Year"
        field: date
        pattern: "2024"
      - label: "History Articles"
        field: category
        pattern: "History"
      - label: "Science Articles"
        field: category
        pattern: "Science"
      - label: "Technology Articles"
        field: category
        pattern: "Technology"
      - label: "Culture Articles"
        field: category
        pattern: "Culture"
      - label: "Mystery Articles"
        field: category
        pattern: "Mystery"
      - label: "Psychology Articles"
        field: category
        pattern: "Psychology"
      - label: "Physics Articles"
        field: category
        pattern: "Physics"
      - label: "Archaeology Articles"
        field: category
        pattern: "Archaeology"
      - label: "Blog Posts"
        field: category
        pattern: "Blog"
      - label: "Welcome Posts"
        field: category
        pattern: "Welcome"
    view_groups:
      - label: "By Category"
        field: category
      - label: "By Author"
        field: author
      - label: "By Year"
        field: date
        pattern: "(\d{4})"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["History", "Science", "Technology", "Culture", "Mystery", "Psychology", "Physics", "Archaeology", "Blog", "Welcome"]}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["Project Paradox Past Team", "Paradox Past"], default: "Project Paradox Past Team"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
