backend:
  name: git-gateway
  branch: main

media_folder: "content/images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary_fields: ["title", "date", "category", "status", "author"]
    sortable_fields: ["date", "title", "category", "author", "status"]
    view_filters:
      - label: "All Articles"
        field: title
        pattern: ".*"
      - label: "Published Articles"
        field: status
        pattern: "published"
      - label: "Draft Articles"
        field: status
        pattern: "draft"
      - label: "Featured Articles"
        field: featured
        pattern: "true"
      - label: "Published This Year"
        field: date
        pattern: "2025"
      - label: "Published Last Year"
        field: date
        pattern: "2024"
      - label: "History Articles"
        field: category
        pattern: "History"
      - label: "Science Articles"
        field: category
        pattern: "Science"
      - label: "Technology Articles"
        field: category
        pattern: "Technology"
      - label: "Culture Articles"
        field: category
        pattern: "Culture"
      - label: "Mystery Articles"
        field: category
        pattern: "Mystery"
      - label: "Psychology Articles"
        field: category
        pattern: "Psychology"
      - label: "Physics Articles"
        field: category
        pattern: "Physics"
      - label: "Archaeology Articles"
        field: category
        pattern: "Archaeology"
      - label: "Blog Posts"
        field: category
        pattern: "Blog"
      - label: "Welcome Posts"
        field: category
        pattern: "Welcome"
    view_groups:
      - label: "By Category"
        field: category
      - label: "By Author"
        field: author
      - label: "By Status"
        field: status
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "datetime", required: true}
      - {label: "Modified Date", name: "modified", widget: "datetime", required: false}
      - {label: "Category", name: "category", widget: "select", options: ["History", "Science", "Technology", "Culture", "Mystery", "Psychology", "Physics", "Archaeology", "Blog", "Welcome"], required: true}
      - {label: "Tags", name: "tags", widget: "list", required: false, hint: "Add relevant tags for this article"}
      - {label: "Slug", name: "slug", widget: "string", required: true, hint: "URL-friendly version of the title"}
      - {label: "Author", name: "author", widget: "select", options: ["Project Paradox Past Team", "Paradox Past"], default: "Project Paradox Past Team", required: true}
      - {label: "Summary", name: "summary", widget: "text", required: true, hint: "Brief description for SEO and article previews"}
      - {label: "Featured Image", name: "image", widget: "image", required: false, hint: "Main image for the article"}
      - {label: "Featured Image Alt Text", name: "image_alt", widget: "string", required: false, hint: "Accessibility description for the featured image"}
      - {label: "Status", name: "status", widget: "select", options: ["published", "draft", "archived"], default: "draft", required: true}
      - {label: "Featured Article", name: "featured", widget: "boolean", default: false, required: false, hint: "Mark as featured on homepage"}
      - {label: "Reading Time", name: "reading_time", widget: "number", required: false, hint: "Estimated reading time in minutes"}
      - {label: "Meta Description", name: "meta_description", widget: "text", required: false, hint: "SEO meta description (150-160 characters)"}
      - {label: "Meta Keywords", name: "meta_keywords", widget: "list", required: false, hint: "SEO keywords"}
      - {label: "Related Articles", name: "related_articles", widget: "list", required: false, hint: "Links to related content"}
      - {label: "Body", name: "body", widget: "markdown", required: true}

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    summary_fields: ["title", "date", "status"]
    sortable_fields: ["date", "title", "status"]
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "datetime", required: true}
      - {label: "Modified Date", name: "modified", widget: "datetime", required: false}
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Template", name: "template", widget: "select", options: ["page", "about", "contact"], default: "page", required: false}
      - {label: "Status", name: "status", widget: "select", options: ["published", "draft"], default: "draft", required: true}
      - {label: "Meta Description", name: "meta_description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Homepage Settings"
        name: "homepage"
        file: "content/settings/homepage.yml"
        fields:
          - {label: "Homepage Title", name: "homepage_title", widget: "string", default: "Watch More Videos on TikTok and Instagram!", required: true}
          - {label: "Homepage Subtitle", name: "homepage_subtitle", widget: "text", required: false}
          - {label: "Hero Background Color", name: "hero_bg_color", widget: "color", default: "#6366f1", required: false}
          - {label: "Show Social Section", name: "show_social_section", widget: "boolean", default: true}
          - label: "Social Media Links"
            name: "social_links"
            widget: "list"
            fields:
              - {label: "Platform", name: "platform", widget: "select", options: ["tiktok", "instagram", "twitter", "facebook", "youtube", "linkedin", "github"], required: true}
              - {label: "Username/Handle", name: "username", widget: "string", required: true, hint: "Your username without @ symbol"}
              - {label: "Full URL", name: "url", widget: "string", required: true, hint: "Complete URL to your profile"}
              - {label: "Display Text", name: "display_text", widget: "string", required: false, hint: "Optional custom text for the link"}
              - {label: "Icon Class", name: "icon_class", widget: "string", default: "fab fa-", required: false, hint: "Font Awesome icon class"}
          - {label: "Featured Articles Section", name: "show_featured_articles", widget: "boolean", default: false}
          - {label: "Articles Section Title", name: "articles_section_title", widget: "string", default: "Latest Articles", required: false}
          - {label: "Max Featured Articles", name: "max_featured_articles", widget: "number", default: 3, required: false}

      - label: "General Settings"
        name: "general"
        file: "content/settings/general.yml"
        fields:
          - {label: "Site Name", name: "site_name", widget: "string", required: true}
          - {label: "Site Description", name: "site_description", widget: "text", required: true}
          - {label: "Site URL", name: "site_url", widget: "string", required: true}
          - {label: "Author", name: "author", widget: "string", required: true}
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Timezone", name: "timezone", widget: "string", default: "UTC", required: true}
          - {label: "Default Language", name: "default_lang", widget: "string", default: "en", required: true}
          - {label: "Theme Color", name: "theme_color", widget: "color", default: "#282a39", required: false}
          - {label: "Background Color", name: "background_color", widget: "color", default: "#ffffff", required: false}
          - {label: "Enable Analytics", name: "analytics_enabled", widget: "boolean", default: false}
          - {label: "Google Analytics ID", name: "google_analytics_id", widget: "string", required: false}
          - {label: "Enable Comments", name: "comments_enabled", widget: "boolean", default: false}
          - {label: "Comments Provider", name: "comments_provider", widget: "select", options: ["disqus", "utterances", "giscus"], required: false}

      - label: "Social Media"
        name: "social"
        file: "content/settings/social.yml"
        fields:
          - {label: "Twitter Username", name: "twitter", widget: "string", required: false}
          - {label: "Facebook Page", name: "facebook", widget: "string", required: false}
          - {label: "Instagram Username", name: "instagram", widget: "string", required: false}
          - {label: "TikTok Username", name: "tiktok", widget: "string", required: false}
          - {label: "LinkedIn Profile", name: "linkedin", widget: "string", required: false}
          - {label: "GitHub Username", name: "github", widget: "string", required: false}
          - {label: "YouTube Channel", name: "youtube", widget: "string", required: false}
          - {label: "Email Contact", name: "email", widget: "string", required: false}

      - label: "Navigation"
        name: "navigation"
        file: "content/settings/navigation.yml"
        fields:
          - label: "Main Menu"
            name: "main_menu"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "External Link", name: "external", widget: "boolean", default: false}

      - label: "SEO Settings"
        name: "seo"
        file: "content/settings/seo.yml"
        fields:
          - {label: "Default Meta Description", name: "default_meta_description", widget: "text"}
          - {label: "Default Meta Keywords", name: "default_meta_keywords", widget: "list"}
          - {label: "Open Graph Image", name: "og_image", widget: "image"}
          - {label: "Twitter Card Type", name: "twitter_card_type", widget: "select", options: ["summary", "summary_large_image"], default: "summary_large_image"}
          - {label: "Site Verification", name: "site_verification", widget: "object", fields: [
              {label: "Google", name: "google", widget: "string", required: false},
              {label: "Bing", name: "bing", widget: "string", required: false},
              {label: "Yandex", name: "yandex", widget: "string", required: false}
            ]}

publish_mode: editorial_workflow
