backend:
  name: git-gateway
  branch: main

media_folder: "content/images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary_fields: ["title", "date", "category", "summary"]
    sortable_fields: ["date", "title", "category"]
    view_filters:
      - label: "History"
        field: category
        pattern: "History"
      - label: "Science"
        field: category
        pattern: "Science"
      - label: "Technology" 
        field: category
        pattern: "Technology"
      - label: "Culture"
        field: category
        pattern: "Culture"
      - label: "Mystery"
        field: category
        pattern: "Mystery"
    view_groups:
      - label: "Category"
        field: category
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["History", "Science", "Technology", "Culture", "Mystery"]}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "Project Paradox Past Team"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
